"""initial schema

Revision ID: ef7aa9548c6a
Revises: 
Create Date: 2026-07-04 17:12:40.714579
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = 'ef7aa9548c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('retry_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.Enum('FIXED', 'LINEAR', 'EXPONENTIAL', name='retrystrategy', native_enum=False), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('base_delay_seconds', sa.Float(), nullable=False),
    sa.Column('max_delay_seconds', sa.Float(), nullable=False),
    sa.Column('backoff_factor', sa.Float(), nullable=False),
    sa.Column('jitter', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('queues', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ALIVE', 'DRAINING', 'DEAD', name='workerstatus', native_enum=False), nullable=False),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index('ix_worker_status_seen', ['status', 'last_heartbeat_at'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_project_org_slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index('ix_hb_worker_ts', ['worker_id', 'created_at'], unique=False)

    op.create_table('queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_sec', sa.Float(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('retry_policy_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_policy_id'], ['retry_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_queue_project_name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('job_type', sa.Enum('IMMEDIATE', 'DELAYED', 'SCHEDULED', 'RECURRING', 'BATCH', name='jobtype', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'SCHEDULED', 'CLAIMED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD', 'CANCELLED', name='jobstate', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_strategy', sa.Enum('FIXED', 'LINEAR', 'EXPONENTIAL', name='retrystrategy', native_enum=False), nullable=False),
    sa.Column('base_delay_seconds', sa.Float(), nullable=False),
    sa.Column('max_delay_seconds', sa.Float(), nullable=False),
    sa.Column('backoff_factor', sa.Float(), nullable=False),
    sa.Column('jitter', sa.Float(), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('depends_on_job_id', sa.String(length=36), nullable=True),
    sa.Column('claimed_by_worker_id', sa.String(length=36), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'idempotency_key', name='uq_job_idem')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_batch', ['batch_id'], unique=False)
        batch_op.create_index('ix_jobs_claim', ['queue_id', 'state', 'priority', 'run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)
        batch_op.create_index('ix_jobs_state_runat', ['state', 'run_at'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_fire_at', sa.DateTime(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_sched_next_fire', ['is_active', 'next_fire_at'], unique=False)

    op.create_table('dead_letter_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('replayed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dead_letter_queue', schema=None) as batch_op:
        batch_op.create_index('ix_dlq_queue', ['queue_id', 'created_at'], unique=False)

    op.create_table('job_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.create_index('ix_exec_job', ['job_id', 'attempt_number'], unique=False)
        batch_op.create_index('ix_exec_worker', ['worker_id'], unique=False)

    op.create_table('job_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['job_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_logs', schema=None) as batch_op:
        batch_op.create_index('ix_joblog_job_ts', ['job_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_joblog_job_ts')

    op.drop_table('job_logs')
    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_exec_worker')
        batch_op.drop_index('ix_exec_job')

    op.drop_table('job_executions')
    with op.batch_alter_table('dead_letter_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_dlq_queue')

    op.drop_table('dead_letter_queue')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_sched_next_fire')

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_state_runat')
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index('ix_jobs_claim')
        batch_op.drop_index('ix_jobs_batch')

    op.drop_table('jobs')
    op.drop_table('queues')
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index('ix_hb_worker_ts')

    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    op.drop_table('projects')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index('ix_worker_status_seen')

    op.drop_table('workers')
    op.drop_table('retry_policies')
    op.drop_table('organizations')
    # ### end Alembic commands ###
